name: musico-api-demo

on:
  push:
    branches:
    - master

jobs:
  build_api:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the API
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'musico-api' }}
      run: |
        cd ./Musico.Web
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
